# Generated by Django 4.2.2 on 2023-06-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result', models.FileField(upload_to='results/')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
